# Generated by Django 3.1.3 on 2020-12-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccesstoken',
            name='page_access_token',
            field=models.TextField(blank=True, help_text='facebook page access token(no expiry)', max_length=250, null=True),
        ),
    ]
